chore(deps): update dependency @types/node to v24 (#25)
* chore(deps): update dependency @types/node to v24

* upgrade all

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Michael Sprauer <Michael.Sprauer@sap.com>

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -31,3 +31,11 @@ jobs:
 
       - name: Build
         run: bun run build
+
+      - name: Fail if dist/** files changed
+        run: |
+          if [[ -n $(git status --porcelain dist/) ]]; then
+            echo "dist/** files have changed after build. Failing workflow."
+            exit 1
+          fi
+        
